# Check `ares-sc2/src/ares/config.yml` for valid config options
# Use this to override those values
# Can add own unique config options here if desired

# Custom values not used by ares
MyBotName: PiG_Bot
MyBotRace: Protoss
# setting ture allows auto upload to aiareana (https://aiarena.net/) on push to `main` branch
# see tutorial on readme before setting to True
AutoUploadToAiarena: False
########################

UseData: False
Debug: True
GameStep: 4
DebugGameStep: 2

DebugOptions:
    # one of: Air, AirVsGround, Ground, GroundAvoidance, AirAvoidance, GroundToAir, TacticalGround
    ActiveGrid: Ground
    ChatDebug: True
    DebugSpawn: False
    ShowPathingCost: False
    ResourceDebug: False
Features:
    TacticalGroundGrid: True